title: "Marklog-example"
description: "Creator of Marklog"
theme: "pixel" # Try: light, dark, ghibli, pixel
author:
  name: Jask
  bio: Full stack developer & pixel artist
  avatar: https://avatars.githubusercontent.com/u/67848850?v=4
social:
  github: https://github.com/respectevery01
  twitter: https://x.com/jaskdon
nav:
  - label: Home
    url: /
  - label: About
    url: /about
